apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-support-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Increased for Windows
  storageClassName: windows-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # For model storage
  storageClassName: windows-storage
  volumeMode: Filesystem